export default {
    index: "Bienvenue!",
    preamble: "Pourquoi ce cours?",
    "first-steps": "1. Premiers pas 🧑‍🎓",
    "saving-account-calculator": "Calculateur d'épargne 💸",
    "pushing-further": "2. Aller plus loin 🚀",
    "stock-market-simulator": "Simulateur boursier 📈",
    "simple-data-analysis": "3. La librairie SDA 🤓",
    "stats-can-census": "Exploiter le recensement 🇨🇦",
    "one-billion-row-challenge": "Le défi du milliard de lignes 😱",
    "web-scraping": "Extraction de données web 🔍",
    "git-and-github": "4. Git et GitHub 🐙",
    "ninja-moves": "Techniques de ninja 🥷",
    inspirations: "Personnes & contenus inspirants 📚",
    "more": "Prochaines leçons...",
    contact: "Contact",
};
