export default {
    index: "Bienvenue!",
    preamble: "Pourquoi ce cours?",
    "first-steps": "1. Premiers pas 🧑‍🎓",
    "saving-account-calculator": "Calculateur d'épargne 💸",
    "pushing-further": "2. Aller plus loin 🚀",
    "stock-market-simulator": "Simulateur boursier 📈",
    "simple-data-analysis": "3. La librairie SDA 🤓",
    "stats-can-census": "Exploiter le recensement 🇨🇦",
    "one-billion-row-challenge": "Le défi du milliard de lignes 😱",
    "web-basics": "4. Les bases du Web 🌐",
    "d3-chart": "Graphiques animés avec D3 🧑‍🎨",
    "d3-map": "Cartes animées avec D3 🗺️",
    "ninja-moves": "Techniques de ninja 🥷",
    inspirations: "Personnes & contenus inspirants 📚",
    "more": "Prochaines leçons...",
    contact: "Contact",
};
