export default {
    index: "Welcome!",
    preamble: "Why this course?",
    "first-steps": "1. First steps 🧑‍🎓",
    "saving-account-calculator": "Savings account calculator 💸",
    "pushing-further": "2. Pushing further 🚀",
    "stock-market-simulator": "Stock market simulator 📈",
    "simple-data-analysis": "3. The SDA library 🤓",
    "stats-can-census": "Wrangling Census data 🇨🇦",
    "one-billion-row-challenge": "One billion row challenge 😱",
    "web-basics": "4. Web basics 🌐",
    "d3-chart": "Animated charts with D3 🧑‍🎨",
    "d3-map": "Animated maps with D3 🗺️",
    "web-scraping": "Web scraping 🔍",
    "git-and-github": "5. Git & GitHub 🐙",
    "ninja-moves": "Ninja moves 🥷",
    inspirations: "Inspiring people & content 📚",
    "more": "More to come...",
    contact: "Contact",
};
